CREATE TABLE TB_PROJETO (
    ID_PROJETO SERIAL PRIMARY KEY,
    PROJETO_NOME VARCHAR(100) NOT NULL
    PROJETO_DESCRICAO TEXT,
    PROJETO_DATA_INICIO DATE,
    PROJETO_DATA_FIM DATE
);

CREATE TABLE TB_ATIVIDADE (
    ID_ATIVIDADE SERIAL PRIMARY KEY,
    ATIVIDADE_NOME VARCHAR(100) NOT NULL,
    ATIVIDADE_ATIVACAO_CAMERA BOOLEAN DEFAULT FALSE,
    ATIVIDADE_ATIVACAO_SITE BOOLEAN DEFAULT FALSE
    -- ID_PROJETO INT REFERENCES TB_PROJETO(ID_PROJETO)
);

CREATE TABLE TB_SESSAO_TRABALHO (
    ID_SESSAO_TRABALHO SERIAL PRIMARY KEY,
    ID_PROJETO INT NOT NULL REFERENCES TB_PROJETO (ID_PROJETO) ON DELETE CASCADE,
    ID_ATIVIDADE INT REFERENCES TB_ATIVIDADE(ID_ATIVIDADE) ON DELETE SET NULL,
    SESSAO_TRABALHO_HORARIO_INICIO TIMESTAMP NOT NULL,
    SESSAO_TRABALHO_HORARIO_FIM TIMESTAMP,
    SESSAO_TRABALHO_HORAS_TRABALHADAS NUMERIC(6,2),
    SESSAO_TRABALHO_DESCRICAO nome VARCHAR(100),
    CONSTRAINT CHK_HORAS_VALIDAS CHECK (SESSAO_TRABALHO_HORAS_TRABALHADAS >= 0)
);
